 const Hogs = [
    {'name': "Mudblood",
     'specialty': "Mediocre magic",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 2.0,
     'highest medal achieved': 'bronze',
     'imageName': "mudblood"
  },
    {'name': "Porkchop",
     'specialty': "Making friends",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 1.6,
     'highest medal achieved': 'silver',
     'imageName': "porkchop"
  },
    {'name': "Cherub",
     'specialty': "truffle finder",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 0.7,
     'highest medal achieved': 'gold',
     'imageName': "cherub"
  },
    {'name': "Piggy smalls",
     'specialty': "Massivity",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 5.1,
     'highest medal achieved': 'platinum',
     'imageName': "piggy_smalls"
  },
    {'name': "Trouble",
     'specialty': "Racing",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 1.7,
     'highest medal achieved': 'gold',
     'imageName': "trouble"
  },
    {'name': "Sobriety",
     'specialty': "Expert Witness",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 2.2,
     'highest medal achieved': 'silver',
     'imageName': "sobriety"
  },
    {'name': "Rainbowdash",
     'specialty': "Union Busting",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 3.7,
     'highest medal achieved': 'wood',
     'imageName': "rainbowdash"
  },
    {'name': "TruffleShuffle",
     'specialty': "Finding truffles",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 4.0,
     'highest medal achieved': 'gold',
     'imageName': "truffleshuffle"
  },
    {'name': "Bay of Pigs",
     'specialty': "Hamphlet Distribution",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 2.8,
     'highest medal achieved': 'diamond',
     'imageName': "bay_of_pigs"
  },
    {'name': "The Prosciutto Concern",
     'specialty': "truffle finder",
     'greased': false,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 2.3,
     'highest medal achieved': 'bronze',
     'imageName': "the_prosciutto_concern"
  },
    {'name': "Galaxy Note",
     'specialty': "Airport Security",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 1.9,
     'highest medal achieved': 'diamond',
     'imageName': "galaxy_note"
  },
    {'name': "Leggo My Eggo",
     'specialty': "Babysitting",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 3.3,
     'highest medal achieved': 'platinum',
     'imageName': "leggo_my_eggo"
  },
    {'name': "Augustus Gloop",
     'specialty': "Vacuum tubes",
     'greased': true,
     'weight as a ratio of hog to LG - 24.7 Cu. Ft. French Door Refrigerator with Thru-the-Door Ice and Water': 4.1,
     'highest medal achieved': 'wood',
     'imageName': "augustus_gloop"
  }
]

export default Hogs
